apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: configtest
spec:
  httpPipeline:
    handlers:
    - name: ratelimit
      type: middleware.http.ratelimit
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://echoserver:80"      