apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: ratelimit
  namespace: poc
spec:
  type: middleware.http.ratelimit
  version: v1
  metadata:
  - name: maxRequestsPerSecond
    value: 2